###############################################################################
## dev 开发环境
###############################################################################
## 数据库设置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seed_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: oVEqvV9eDElBwqDK/0Q8CCSM5ng+1XIdhNaiZkiucirCQ40ciDdh9NVfbkS4TtQSFXwEYMU9F8nXxtFT9qLQbA==
    publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKiGbrG4cyykog9xteJeaS+XrYVmxAMYB+fBxayVGTc41+f/ncMb7Hs6vUAVdRxc0/HRaboPbPLQYQY+eSfdslkCAwEAAQ==
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    validationQuery: SELECT 1
    filters: stat,log4j,wall,config
###############################################################################
## redis配置
  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 10000ms
    jedis:
      pool:
        max-active: 50
        max-idle: 5
        min-idle: 0
        max-wait: 10000ms
###############################################################################
## 日志配置路径
logging:
  config: classpath:log4j2-dev.xml
###############################################################################
## swagger配置
swagger:
  enable: true
###############################################################################
